KraviaDepartments/Models/Department.cs
using System.ComponentModel.DataAnnotations;

namespace KraviaDepartments.Models
{
    public class Department
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "You should input Name Of Department")]
        [StringLength(50, MinimumLength = 5, ErrorMessage = "Length of string 5 to 50 symbols")]
        [DataType(DataType.Text)]
        public string Name { get; set; }

        [Required(ErrorMessage = "You should input Address of Your departmant")]
        [StringLength(50, MinimumLength = 5, ErrorMessage = "Length of string 5 to 50 symbols")]
        [DataType(DataType.Text)]
        public string Address { get; set; }

        [Required(ErrorMessage = "You should input Name Of Director")]
        [StringLength(50, MinimumLength = 5, ErrorMessage = "Length of string 5 to 50 symbols")]
        [DataType(DataType.Text)]
        public string HeadOfDepartment { get; set; }

        [Range(2, 10000, ErrorMessage = "Undefined number ")]
        [Required(ErrorMessage = "You should input Team Size")]
        public int TeamSize { get; set; }

        [Range(2, 10000, ErrorMessage = "Undefined number ")]
        [Required(ErrorMessage = "Please, enter average salary")]
        [DataType(DataType.Currency)]
        public double AverageSalary { get; set; }
    }
}

KraviaDepartments/Models/DepartmentContext.cs
using Microsoft.EntityFrameworkCore;

namespace KraviaDepartments.Models
{
    public class DepartmentContext : DbContext
    {
        public DbSet<Department> Departments { get; set; }

        public DepartmentContext(DbContextOptions<DepartmentContext> options) : base(options)
        {
        }
    }
}

KraviaDepartments/Models/ErrorViewModel.cs
using System;

namespace KraviaDepartments.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

KraviaDepartments/Controllers/DataController.cs
using System.Threading.Tasks;
using KraviaDepartments.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace KraviaDepartments.Controllers
{
    public class DataController : Controller
    {
        private DepartmentContext departmentContext;

        public DataController(DepartmentContext context) => departmentContext = context;

        public async Task<IActionResult> Index() => View(await departmentContext.Departments.ToListAsync());

        public IActionResult AddNewNote() => View();

        [HttpPost]
        public async Task<IActionResult> AddNewNote(Department department)
        {
            if (ModelState.IsValid)
            {
                departmentContext.Departments.Add(department);
                await departmentContext.SaveChangesAsync();
            }
            ViewBag["SomeTrouble"] = string.Format(ModelState.ValidationState + " Errors count = " + ModelState.ErrorCount);
            return RedirectToAction("Index", "Home");
        }
    }
}

KraviaDepartments/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using KraviaDepartments.Models;

namespace KraviaDepartments.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index() => View();

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

KraviaDepartments/Views/Data/AddNewNote.cshtml
@model KraviaDepartments.Models.Department
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>AddNewNote</title>
</head>
<body>
    <form asp-action="AddNewNote" asp-controller="Data">
        @Html.ValidationSummary(true)

        <div class="form-group">
            <label asp-for="Name" class="control-label">Name Of Department</label>
            <input type="text" asp-for="Name" class="form-control" />
        </div>
        <div class="form-group">
            <label asp-for="Address" class="control-label">Address</label>
            <input type="text" asp-for="Address" class="form-control" />
        </div>
        <div class="form-group">
            <label asp-for="HeadOfDepartment" class="control-label">Enter name for Head Of Department</label>
            <input type="text" asp-for="HeadOfDepartment" class="form-control" />
        </div>
        <div class="form-group">
            <label asp-for="TeamSize" class="control-label">How many teammates ?</label>
            <input type="number" asp-for="TeamSize" class="form-control" />
        </div>
        <div class="form-group">
            <label asp-for="AverageSalary" class="control-label">Input average salary for teammates</label>
            <input type="number" asp-for="AverageSalary" class="form-control" />
        </div>
        <div class="form-group">
            <input type="submit" value="Add" class="btn btn-default" />
        </div>
    </form>
</body>
</html>

KraviaDepartments/Views/Data/Index.cshtml
@model IEnumerable<KraviaDepartments.Models.Department>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>IndexData</title>
</head>
<body>
    @Html.ActionLink("Add new Department", "AddNewNote");
    <table class="table">
        <tr><td></td><td>TeamName</td><td>Address</td><td>TeamSize</td><td>HeadOfDepartment</td><td>AverageSalary</td></tr>
        @foreach (var item in Model)
        {
            <tr><td>@item.Name</td><td>@item.Address</td><td>@item.TeamSize</td><td>@item.HeadOfDepartment</td><td>@item.AverageSalary</td></tr>
        }
    </table>
</body>
</html>

KraviaDepartments/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

KraviaDepartments/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

KraviaDepartments/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

@Html.ActionLink("Press To Add New department", "Index", "Data");

KraviaDepartments/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - KraviaDepartments</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">KraviaDepartments</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - KraviaDepartments</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>